# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('system', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Identifier',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('telecom', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='identifier',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='RestAPI.Patient'),
        ),
    ]
