# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_auto_20180606_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_org', to='RestAPI.Organization'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='RestAPI.Patient'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='RestAPI.Patient'),
        ),
        migrations.AlterField(
            model_name='name',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='RestAPI.Patient'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='communication',
            table='Communication',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='name',
            table='Name',
        ),
    ]
