# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_auto_20180607_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='resource_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_org', to='RestAPI.Organization'),
        ),
    ]
