# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_auto_20180607_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='RestAPI.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_org', to='RestAPI.Organization'),
        ),
    ]
