param = {
    "input": {
        "Patient": {[
            {
                "resource_type": "Patient",
                "identifier__type": "MRN",
                "identifier__value": "48-14-000010",
                "identifier__facility": "048",
                "identifier__start": "2014-09-30 19:51:52.373",
                "identifier__end": null,
                "name__suffix": null,
                "name__prefix": "นาย",
                "name__middle_name": null,
                "name__family_name": "จงหมั่น",
                "name__given_name": "สมพงษ์",
                "name__language": "TH",
                "address__district": "บางขุนเทียน",
                "address__line": "113/77    รุ่งเพชรคอนโดมีเนียม  ซ.66 พระราม 2 ",
                "address__state_desc": "กรุงเทพฯ",
                "address__country": "THA",
                "address__zipcode": "10150",
                "address__city": "แสมดำ",
                "communication__commu_language": "TH",
                "communication__commu_preferred": "True",
                "contact__system": "phone",
                "contact__value": "0805201996",
                "extension__vip_type": null,
                "row_id": "10",
                "birth_date": "1975-04-15",
                "deceased": "False",
                "gender": "M",
                "deceased_datetime": null,
                "nationality": "TH",
                "religion": "พุทธ (BUDDHISM)",
                "marital_status": "โสด (Single)"
            },
            {
                "resource_type": "Patient",
                "identifier__type": "MRN",
                "identifier__value": "48-14-000010",
                "identifier__facility": "048",
                "identifier__start": "2014-09-30 19:51:52.373",
                "identifier__end": null,
                "name__suffix": null,
                "name__prefix": "นาย",
                "name__middle_name": null,
                "name__family_name": "จงหมั่น",
                "name__given_name": "สมพงษ์",
                "name__language": "TH",
                "address__district": "บางขุนเทียน",
                "address__line": "113/77    รุ่งเพชรคอนโดมีเนียม  ซ.66 พระราม 2 ",
                "address__state_desc": "กรุงเทพฯ",
                "address__country": "THA",
                "address__zipcode": "10150",
                "address__city": "แสมดำ",
                "communication__commu_language": "TH",
                "communication__commu_preferred": "True",
                "contact__system": "email",
                "contact__value": "sompong.jo@glsict.com",
                "extension__vip_type": null,
                "row_id": "10",
                "birth_date": "1975-04-15",
                "deceased": "False",
                "gender": "M",
                "deceased_datetime": null,
                "nationality": "TH",
                "religion": "พุทธ (BUDDHISM)",
                "marital_status": "โสด (Single)"
            },
            {
                "resource_type": "Patient",
                "identifier__type": "NID",
                "identifier__value": "3830100203814",
                "identifier__facility": "038",
                "identifier__start": "2011-06-07 00:00:00.0",
                "identifier__end": "2018-04-14 00:00:00.0",
                "name__suffix": null,
                "name__prefix": "นาย",
                "name__middle_name": null,
                "name__family_name": "จงหมั่น",
                "name__given_name": "สมพงษ์",
                "name__language": "TH",
                "address__district": "บางขุนเทียน",
                "address__line": "113/77    รุ่งเพชรคอนโดมีเนียม  ซ.66 พระราม 2 ",
                "address__state_desc": "กรุงเทพฯ",
                "address__country": "THA",
                "address__zipcode": "10150",
                "address__city": "แสมดำ",
                "communication__commu_language": "TH",
                "communication__commu_preferred": "True",
                "contact__system": "phone",
                "contact__value": "0805201996",
                "extension__vip_type": null,
                "row_id": "10",
                "birth_date": "1975-04-15",
                "deceased": "False",
                "gender": "M",
                "deceased_datetime": null,
                "nationality": "TH",
                "religion": "พุทธ (BUDDHISM)",
                "marital_status": "โสด (Single)"
            },
            {
                "resource_type": "Patient",
                "identifier__type": "NID",
                "identifier__value": "3830100203814",
                "identifier__facility": "038",
                "identifier__start": "2011-06-07 00:00:00.0",
                "identifier__end": "2018-04-14 00:00:00.0",
                "name__suffix": null,
                "name__prefix": "นาย",
                "name__middle_name": null,
                "name__family_name": "จงหมั่น",
                "name__given_name": "สมพงษ์",
                "name__language": "TH",
                "address__district": "บางขุนเทียน",
                "address__line": "113/77    รุ่งเพชรคอนโดมีเนียม  ซ.66 พระราม 2 ",
                "address__state_desc": "กรุงเทพฯ",
                "address__country": "THA",
                "address__zipcode": "10150",
                "address__city": "แสมดำ",
                "communication__commu_language": "TH",
                "communication__commu_preferred": "True",
                "contact__system": "email",
                "contact__value": "sompong.jo@glsict.com",
                "extension__vip_type": null,
                "row_id": "10",
                "birth_date": "1975-04-15",
                "deceased": "False",
                "gender": "M",
                "deceased_datetime": null,
                "nationality": "TH",
                "religion": "พุทธ (BUDDHISM)",
                "marital_status": "โสด (Single)"
            }
        ]

        },
        "order": {[
            {
                "row_id": "423543",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "A010",
                "OrderItem__name": "Complete Blood Count",
                "OrderItemType__identifier": "106336",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423544",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "D382",
                "OrderItem__name": "Stool Examination and Occult Blood",
                "OrderItemType__identifier": "106337",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423545",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C007",
                "OrderItem__name": "Lipid profile (Glu,Chol,Trig,HDL,LDL)",
                "OrderItemType__identifier": "106338",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423546",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C530",
                "OrderItem__name": "Blood Urea Nitrogen",
                "OrderItemType__identifier": "106339",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423547",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C521",
                "OrderItem__name": "Creatinine (plus eGFR)",
                "OrderItemType__identifier": "106340",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423548",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C610",
                "OrderItem__name": "AST (Aspartate Transaminase)",
                "OrderItemType__identifier": "106341",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423549",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C600",
                "OrderItem__name": "ALT (Alanine Transaminase)",
                "OrderItemType__identifier": "106342",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423550",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C580",
                "OrderItem__name": "ALP (Alkaline Phosphatase)",
                "OrderItemType__identifier": "106343",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423551",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "C120",
                "OrderItem__name": "Uric Acid",
                "OrderItemType__identifier": "106344",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423552",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "N050",
                "OrderItem__name": "Prostatic Specific Antigen (PSA)",
                "OrderItemType__identifier": "106345",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423553",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "N420",
                "OrderItem__name": "Carcinoembryonic Antigen (CEA) (BGH)",
                "OrderItemType__identifier": "106346",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423554",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "D111",
                "OrderItem__name": "Urine Examination",
                "OrderItemType__identifier": "106347",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423555",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "N010",
                "OrderItem__name": "Thyroid Stimulating Hormone(TSH)",
                "OrderItemType__identifier": "106348",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423556",
                "order_number": "1717227",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "N030",
                "OrderItem__name": "Thyroxine Free (Free T4)",
                "OrderItemType__identifier": "106349",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "SAMPLCOL",
                "OrderStatus__display": "Specimen Collected",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423557",
                "order_number": "1717228",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "142026",
                "OrderItem__name": "EKG (ECG Cardiac)",
                "OrderItemType__identifier": "5717",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "1407",
                "OrderCategory__display": "เครื่องมือแพทย์ศูนย์หัวใจ"
            },
            {
                "row_id": "423558",
                "order_number": "1717228",
                "encounter": "O48-15-015283",
                "physician": "048150230",
                "OrderItem__code": "19377",
                "OrderItem__name": "ค่าแพทย์อ่านผล EKG",
                "OrderItemType__identifier": "6767",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "EXCUT",
                "OrderStatus__display": "Executed",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "1407",
                "OrderCategory__display": "เครื่องมือแพทย์ศูนย์หัวใจ"
            },
            {
                "row_id": "423559",
                "order_number": "1717228",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "142025",
                "OrderItem__name": "Exercise Stress Test (EST) (Package)",
                "OrderItemType__identifier": "5716",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "1407",
                "OrderCategory__display": "เครื่องมือแพทย์ศูนย์หัวใจ"
            },
            {
                "row_id": "423560",
                "order_number": "1717228",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "11332",
                "OrderItem__name": "ค่าเวชภัณฑ์ศูนย์ Non Invasive",
                "OrderItemType__identifier": "5248",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "1407",
                "OrderCategory__display": "เครื่องมือแพทย์ศูนย์หัวใจ"
            },
            {
                "row_id": "423561",
                "order_number": "1717229",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "140285",
                "OrderItem__name": "วัดสายตาและตาบอดสี",
                "OrderItemType__identifier": "5422",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "1404",
                "OrderCategory__display": "เครื่องมือแพทย์ศูนย์ตา"
            },
            {
                "row_id": "423562",
                "order_number": "1717230",
                "encounter": "O48-15-015283",
                "physician": "048140334",
                "OrderItem__code": "19012",
                "OrderItem__name": "ค่าตรวจสุขภาพ(PE Checkup)",
                "OrderItemType__identifier": "6540",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "EXCUT",
                "OrderStatus__display": "Executed",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "19",
                "OrderCategory__display": "ค่าแพทย์"
            },
            {
                "row_id": "423563",
                "order_number": "1717231",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "10061",
                "OrderItem__name": "ค่าตรวจห้องวิเคราะห์(Package)",
                "OrderItemType__identifier": "5149",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT1",
                "OrderCategory__display": "Lab"
            },
            {
                "row_id": "423564",
                "order_number": "1717232",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "03MICKSD",
                "OrderItem__name": "CK-ค่าเครื่องมือแพทย์ตรวจเอกซเรย์ปกติ (Standard Diagnostic Imaging)",
                "OrderItemType__identifier": "1121",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "423565",
                "order_number": "1717232",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "03MIUS",
                "OrderItem__name": "ค่าเครื่องมือแพทย์ตรวจอัลตราซาวด์ (Ultrasound)",
                "OrderItemType__identifier": "1138",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "423566",
                "order_number": "1717233",
                "encounter": "O48-15-015283",
                "physician": "048150230",
                "OrderItem__code": "19378",
                "OrderItem__name": "ค่าแพทย์อ่านผล EST",
                "OrderItemType__identifier": "6768",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "EXCUT",
                "OrderStatus__display": "Executed",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "19",
                "OrderCategory__display": "ค่าแพทย์"
            },
            {
                "row_id": "423567",
                "order_number": "1717233",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "12087",
                "OrderItem__name": "ค่าคูปองอาหารตรวจสุขภาพ",
                "OrderItemType__identifier": "5276",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "12",
                "OrderCategory__display": "ค่าของใช้"
            },
            {
                "row_id": "423568",
                "order_number": "1717233",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "12051",
                "OrderItem__name": "ค่าสมุดรายงานผลตรวจ",
                "OrderItemType__identifier": "5272",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "12",
                "OrderCategory__display": "ค่าของใช้"
            },
            {
                "row_id": "423569",
                "order_number": "1717233",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "18028",
                "OrderItem__name": "Note to cashier $$$$",
                "OrderItemType__identifier": "6425",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "18",
                "OrderCategory__display": "ค่าบริการอื่นๆ"
            },
            {
                "row_id": "423570",
                "order_number": "1717234",
                "encounter": "O48-15-015283",
                "physician": "048150443",
                "OrderItem__code": "03GX01",
                "OrderItem__name": "Chest PA",
                "OrderItemType__identifier": "106350",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "REVIW",
                "OrderStatus__display": "Reviewed",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "423571",
                "order_number": "1717234",
                "encounter": "O48-15-015283",
                "physician": "048150443",
                "OrderItem__code": "03UT22",
                "OrderItem__name": "Ultrasound Whole Abdomen",
                "OrderItemType__identifier": "106351",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "REVIW",
                "OrderStatus__display": "Reviewed",
                "OrderPeriod__start": "2015-08-11 07:19:55.55",
                "OrderPeriod__end": "2015-08-12 07:19:55.55",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424070",
                "order_number": "1717392",
                "encounter": "O48-15-015283",
                "physician": "48CHK",
                "OrderItem__code": "03MISD",
                "OrderItem__name": "ค่าเครื่องมือแพทย์ตรวจเอกซเรย์ปกติ (Standard Diagnostic Imaging)",
                "OrderItemType__identifier": "1136",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 09:30:37.177",
                "OrderPeriod__end": "2015-08-12 09:30:37.177",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424071",
                "order_number": "1717393",
                "encounter": "O48-15-015283",
                "physician": "048150443",
                "OrderItem__code": "03GX76",
                "OrderItem__name": "Chest Lt.Lateral",
                "OrderItemType__identifier": "106544",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "REVIW",
                "OrderStatus__display": "Reviewed",
                "OrderPeriod__start": "2015-08-11 09:30:37.177",
                "OrderPeriod__end": "2015-08-12 09:30:37.177",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424358",
                "order_number": "1717501",
                "encounter": "O48-15-015283",
                "physician": "048140334",
                "OrderItem__code": "18028",
                "OrderItem__name": "Note to cashier $$$$",
                "OrderItemType__identifier": "6425",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 10:39:37.81",
                "OrderPeriod__end": "2015-08-12 10:39:37.81",
                "OrderCategory__code": "18",
                "OrderCategory__display": "ค่าบริการอื่นๆ"
            },
            {
                "row_id": "424388",
                "order_number": "1717517",
                "encounter": "O48-15-015283",
                "physician": "048140334",
                "OrderItem__code": "18028",
                "OrderItem__name": "Note to cashier $$$$",
                "OrderItemType__identifier": "6425",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 10:49:13.007",
                "OrderPeriod__end": "2015-08-12 10:49:13.007",
                "OrderCategory__code": "18",
                "OrderCategory__display": "ค่าบริการอื่นๆ"
            },
            {
                "row_id": "424394",
                "order_number": "1717522",
                "encounter": "O48-15-015283",
                "physician": "048140333",
                "OrderItem__code": "19001L0",
                "OrderItem__name": "ค่าตรวจรักษากรณีผู้ป่วยนอกครั้งแรก ระดับ 1",
                "OrderItemType__identifier": "6494",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "CANCLD",
                "OrderStatus__display": "Cancelled",
                "OrderPeriod__start": "2015-08-11 10:58:35.553",
                "OrderPeriod__end": "2015-08-12 10:58:35.553",
                "OrderCategory__code": "19",
                "OrderCategory__display": "ค่าแพทย์"
            },
            {
                "row_id": "424404",
                "order_number": "1717526",
                "encounter": "O48-15-015283",
                "physician": "048140334",
                "OrderItem__code": "18028",
                "OrderItem__name": "Note to cashier $$$$",
                "OrderItemType__identifier": "6425",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 10:48:46.727",
                "OrderPeriod__end": "2015-08-12 10:48:46.727",
                "OrderCategory__code": "18",
                "OrderCategory__display": "ค่าบริการอื่นๆ"
            },
            {
                "row_id": "424408",
                "order_number": "1717529",
                "encounter": "O48-15-015283",
                "physician": "048140333",
                "OrderItem__code": "03MICT",
                "OrderItem__name": "ค่าเครื่องมือแพทย์ตรวจเอกซเรย์คอมพิวเตอร์ (Xray Computer)",
                "OrderItemType__identifier": "1125",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "CANCLD",
                "OrderStatus__display": "Cancelled",
                "OrderPeriod__start": "2015-08-11 11:01:34.337",
                "OrderPeriod__end": "2015-08-12 11:01:34.337",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424409",
                "order_number": "1717530",
                "encounter": "O48-15-015283",
                "physician": "048140333",
                "OrderItem__code": "03XCT5",
                "OrderItem__name": "CT Chest",
                "OrderItemType__identifier": "106629",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "CANCLD",
                "OrderStatus__display": "Cancelled",
                "OrderPeriod__start": "2015-08-11 11:01:34.337",
                "OrderPeriod__end": "2015-08-12 11:01:34.337",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424415",
                "order_number": "1717536",
                "encounter": "O48-15-015283",
                "physician": "048140334",
                "OrderItem__code": "18028",
                "OrderItem__name": "Note to cashier $$$$",
                "OrderItemType__identifier": "6425",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 11:03:23.983",
                "OrderPeriod__end": "2015-08-12 11:03:23.983",
                "OrderCategory__code": "18",
                "OrderCategory__display": "ค่าบริการอื่นๆ"
            },
            {
                "row_id": "424430",
                "order_number": "1717543",
                "encounter": "O48-15-015283",
                "physician": "048140333",
                "OrderItem__code": "03MICT",
                "OrderItem__name": "ค่าเครื่องมือแพทย์ตรวจเอกซเรย์คอมพิวเตอร์ (Xray Computer)",
                "OrderItemType__identifier": "1125",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 11:18:30.61",
                "OrderPeriod__end": "2015-08-12 11:18:30.61",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424431",
                "order_number": "1717544",
                "encounter": "O48-15-015283",
                "physician": "048150443",
                "OrderItem__code": "03XCT82",
                "OrderItem__name": "CT Detection for Early Lung Cancer",
                "OrderItemType__identifier": "106632",
                "OrderItemType__identifier_type": "REQUESTDETAIL",
                "OrderStatus__code": "REVIW",
                "OrderStatus__display": "Reviewed",
                "OrderPeriod__start": "2015-08-11 11:18:30.61",
                "OrderPeriod__end": "2015-08-12 11:18:30.61",
                "OrderCategory__code": "ORDCT2",
                "OrderCategory__display": "X-Ray"
            },
            {
                "row_id": "424739",
                "order_number": "1717697",
                "encounter": "O48-15-015283",
                "physician": "048140333",
                "OrderItem__code": "19001L1",
                "OrderItem__name": "ค่าตรวจรักษากรณีผู้ป่วยนอกครั้งแรก ระดับ 2",
                "OrderItemType__identifier": "6496",
                "OrderItemType__identifier_type": "OrderCatalogItem",
                "OrderStatus__code": "RAISED",
                "OrderStatus__display": "Raised",
                "OrderPeriod__start": "2015-08-11 14:02:36.24",
                "OrderPeriod__end": "2015-08-12 14:02:36.24",
                "OrderCategory__code": "19",
                "OrderCategory__display": "ค่าแพทย์"
            }
        ]


        },
        "encounter": {[
    {
        "identifier": "E48-15-001215",
        "status": "DISCH",
        "class": "INPAT",
        "type": "AEPAT",
        "is_urgency": "True",
        "admit_source": null,
        "patient": "48-15-003475",
        "service_provider__code": "48W1",
        "service_provider__name": "Ward 5",
        "service_provider_description": "Ward 5",
        "encounter_location__start": null,
        "encounter_location__enloc_id_loc_system": "BCONN",
        "encounter_location__enloc_id_loc_value": "48W1",
        "encounter_location__enloc_id_loc_type": "Location.Code",
        "encounter_location__enloc_id_loc_use": "official",
        "encounter_location__enloc_phy_loc_system": "HL7",
        "encounter_location__enloc_phy_loc_code": "wa",
        "encounter_location__enloc_phy_loc_display": "Ward",
        "encounter_location__enloc_loc_name": "Ward 5",
        "encounter_location__enloc_loc_desc": "Pac_Ward",
        "encounter_location__enloc_loc_addr": null,
        "period__start": "2015-04-05 16:14:43.25",
        "period__end": "2015-04-09 14:55:42.82",
        "participants__practitioner": "048140522",
        "priority__code": "3",
        "priority__display": "Yellow",
        "priority__system_source": "BCONN",
        "extension__is_trauma": "True",
        "extension__medical_discharge_datetime": "2015-04-09 11:11:07.56",
        "extension__discharge_datetime": "2015-04-09 14:55:42.82",
        "extension__discharge_condition": "Improved",
        "extension__discharge_type": "With Approval",
        "identifier_list__system": "BCONN",
        "identifier_list__use": "official",
        "identifier_list__type": "emergency",
        "identifier_list__value": "E48-15-001215"
    }
]

        },
        "hisuser": {
            {
                "username": "00437",
                "password": "6ZoYxCjLONXyYIU2eJIuAw==",
                "license": "ท.8890",
                "status_flag": "N",
                "source": "BCONN",
                "role": "Dental Doctor"
            }
        

        },
        "observation": {

        },
        "Practitioner": {[
            {
                "identifier__type": "employee_id+his_code",
                "identifier__value": "048140361+048140361",
                "specialty__specialty_code": 12,
                "specialty__specialty_desc": "Anesthesiology",
                "active": "True",
                "name__title": null,
                "name__given_name": "ศรินญา",
                "name__middle_name": null,
                "name__family_name": "จันทะวงศ์, พญ.",
                "period__start_date": "2014-08-15 10:05:13.457",
                "period__end_date": null,
                "role__code": "CPTEN24",
                "role__desc": "Medical Doctor",
                "qualification__system": "BCONN",
                "qualification__code": "Doctor",
                "qualification__display": "Doctor",
                "license": "28267",
                "location__enloc_id_loc_system": "BCONN",
                "location__enloc_id_loc_value": "48CAR",
                "location__enloc_id_loc_type": "48CAR",
                "location__enloc_id_loc_use": "official",
                "location__enloc_phy_loc_system": "HL7",
                "location__enloc_phy_loc_code": "wa",
                "location__enloc_phy_loc_display": "Ward",
                "location__enloc_loc_name": "Heart Center",
                "location__enloc_loc_desc": "Execute",
                "location__enloc_loc_addr": null
            }
        ]

        },
        "referralrequest": {[
            {
                "identifier": "43",
                "description": "ตัวแทนประกันอยากให้มารักษาต่อที่  BKN",
                "requester": "AIA จำกัด บริษัท",
                "patient_id": "48-15-003475",
                "encounter_id": "E48-15-001215"
            }
        ]

        }
    },
    "output": {

    }
]
